package report

// Lang specifies the output language for terminal and LLM-enhanced reports.
type Lang string

const (
	LangEN Lang = "en"
	LangJA Lang = "ja"
)

// labels holds localized strings used in report output.
type labelSet struct {
	Summary             string
	AttackChainDetected string
	AttackChainTitle    string
	NoFindings          string
	Evidence            string
	Fix                 string
	Reference           string
	Generated           string
	Duration            string
	Target              string
	Layers              string
	Layer               string
	Attacker            string
	Arrow               string
}

var allLabels = map[Lang]labelSet{
	LangEN: {
		Summary:             "SUMMARY",
		AttackChainDetected: "ATTACK CHAIN DETECTED",
		AttackChainTitle:    "ATTACK CHAIN",
		NoFindings:          "No findings",
		Evidence:            "Evidence",
		Fix:                 "Fix",
		Reference:           "Reference",
		Generated:           "Generated by 1scan",
		Duration:            "Duration",
		Target:              "Target",
		Layers:              "Layers",
		Layer:               "Layer",
		Attacker:            "An attacker",
		Arrow:               "→",
	},
	LangJA: {
		Summary:             "サマリ",
		AttackChainDetected: "攻撃チェーン検出",
		AttackChainTitle:    "攻撃チェーン",
		NoFindings:          "問題なし",
		Evidence:            "証拠",
		Fix:                 "修正方法",
		Reference:           "参考",
		Generated:           "1scan が生成",
		Duration:            "所要時間",
		Target:              "対象",
		Layers:              "レイヤー",
		Layer:               "レイヤー",
		Attacker:            "攻撃者が",
		Arrow:               "→",
	},
}

// getLabels returns the label set for the given language, defaulting to EN.
func getLabels(lang Lang) labelSet {
	if l, ok := allLabels[lang]; ok {
		return l
	}
	return allLabels[LangEN]
}

// ParseLang converts a string to a Lang, defaulting to EN for unknown values.
func ParseLang(s string) Lang {
	switch s {
	case "ja", "JA", "japanese":
		return LangJA
	default:
		return LangEN
	}
}
